# REF: https://github.com/SillyTavern/SillyTavern/blob/13099c43a93afc23a7fb7544e53024e188fbe537/default/config.yaml

whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
  - char-archive.evulid.cc

# Expose ST so Railway can forward it to a domain
listen: true
port: ${PORT}
# IPv6 support for those who need it
protocol:
    ipv4: true
    ipv6: ${SILLYTAVERN_ENABLE_IPV6}
dnsPreferIPv6: ${SILLYTAVERN_PREFER_IPV6}

# We'll be using multi-user instead
whitelistMode: false
# Enable multi-user
enableUserAccounts: true
# Whether to hide user list or not
enableDiscreetLogin: ${SILLYTAVERN_DISCREET_LOGIN}
# For some reason ST wouldn't let me expose ST if this is set to false
securityOverride: true

logging:
  enableAccessLog: true
  # Minimum log level to display (DEBUG = 0, INFO = 1, WARN = 2, ERROR = 3)
  minLogLevel: ${SILLYTAVERN_LOG_LEVEL}
