FROM ghcr.io/sillytavern/sillytavern:1.12.14

RUN apk update && apk add gettext

RUN mkdir ./persist

RUN mv ./config ./_config || mkdir ./_config && \
	mv ./data ./_data || mkdir ./_data && \
	mv ./plugins ./_plugins || mkdir ./_plugins

RUN ln -sf ./persist/config ./config && \
	ln -sf ./persist/data ./data && \
	ln -sf ./persist/plugins ./plugins

COPY wrapper.sh ./
COPY config.1.12.14.yaml ./config.template.yaml

RUN chmod +x ./wrapper.sh

ENTRYPOINT ["./wrapper.sh"]
