FROM ghcr.io/sillytavern/sillytavern:1.12.6

# So that we only need one volume
RUN mkdir ./persist

# Move all the necessary directories for later
RUN \
  mv ./config ./_config || true && \
  mv ./data ./_data || true && \
  mv ./plugins ./_plugins || true && \
  ln -sf ./persist/config ./config && \
  ln -sf ./persist/data ./data && \
  ln -sf ./persist/plugins ./plugins

COPY entrypoint.sh ./

RUN chmod +x ./entrypoint.sh

CMD ["./entrypoint.sh"]
